# Generated by Django 3.2.9 on 2021-12-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rba', '0002_auto_20211129_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='cs',
            name='map_embed_url',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
    ]
