# Generated by Django 3.2.9 on 2021-12-07 14:37

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rba', '0004_cs_es_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cs',
            name='study_area',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='1.1 Define the Study Area'),
        ),
    ]
