# Generated by Django 3.2.9 on 2021-12-07 15:14

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rba', '0005_cs_study_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='cs',
            name='ecosystem_services',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='1.3 Define core Ecosystem Services'),
        ),
        migrations.AddField(
            model_name='cs',
            name='future_scenarios',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='1.4 Define future scenarios'),
        ),
        migrations.AddField(
            model_name='cs',
            name='policy_objectives',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='1.2 Define Policy objectives'),
        ),
    ]
