# Generated by Django 3.2.9 on 2021-12-12 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rba', '0007_cs_phase2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CS_phase2',
            new_name='CSphase2',
        ),
    ]
