# Generated by Django 3.2.9 on 2021-12-12 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rba', '0008_rename_cs_phase2_csphase2'),
    ]

    operations = [
        migrations.CreateModel(
            name='M2MPhase2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rba.cs')),
                ('phase_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rba.csphase2')),
            ],
        ),
        migrations.AddField(
            model_name='cs',
            name='phase2',
            field=models.ManyToManyField(blank=True, through='rba.M2MPhase2', to='rba.CSphase2'),
        ),
    ]
