# Generated by Django 3.2.9 on 2021-12-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rba', '0009_auto_20211212_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='csphase2',
            name='title',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
