# Generated by Django 3.2.9 on 2021-12-13 15:58

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rba', '0010_csphase2_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='csphase2',
            name='impact_chain',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='2.6 Source / Pressure / Pathway / Receptor Relationships'),
        ),
    ]
