# Generated by Django 3.2.9 on 2021-12-13 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rba', '0011_csphase2_impact_chain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csphase2',
            name='condition_type',
        ),
    ]
