# Generated by Django 3.2.9 on 2021-12-14 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0028_auto_20211213_1143'),
        ('rba', '0014_alter_csphase2_condition_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase2Pressures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rba.csphase2')),
                ('pressure_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools4msp.pressure')),
            ],
        ),
        migrations.AddField(
            model_name='csphase2',
            name='pressure_list',
            field=models.ManyToManyField(blank=True, through='rba.Phase2Pressures', to='tools4msp.Pressure'),
        ),
    ]
