# Generated by Django 3.2.9 on 2021-12-14 15:49

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rba', '0016_auto_20211214_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csphase2',
            name='pressure_description',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
