# Generated by Django 3.2.9 on 2021-12-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0028_auto_20211213_1143'),
        ('rba', '0017_alter_csphase2_pressure_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csphase2',
            name='pressure_list',
            field=models.ManyToManyField(blank=True, through='rba.Phase2Pressures', to='tools4msp.Pressure', verbose_name='Presures'),
        ),
    ]
