# Generated by Django 3.2.9 on 2021-12-15 15:04

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rba', '0018_alter_csphase2_pressure_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csphase2',
            name='layer',
        ),
        migrations.RemoveField(
            model_name='csphase2',
            name='pressure_description',
        ),
        migrations.AddField(
            model_name='phase2pressures',
            name='layer',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='phase2pressures',
            name='pressure_description',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
