# Generated by Django 3.2.9 on 2021-12-20 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0028_auto_20211213_1143'),
        ('rba', '0019_auto_20211215_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csphase2',
            name='pressure_list',
            field=models.ManyToManyField(blank=True, through='rba.Phase2Pressures', to='tools4msp.Pressure', verbose_name='Pressures'),
        ),
        migrations.CreateModel(
            name='Phase2uses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rba.csphase2')),
                ('use_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools4msp.use')),
            ],
        ),
        migrations.AddField(
            model_name='csphase2',
            name='use_list',
            field=models.ManyToManyField(blank=True, through='rba.Phase2uses', to='tools4msp.Use', verbose_name='Uses'),
        ),
    ]
