# Generated by Django 3.2.9 on 2021-12-21 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0028_auto_20211213_1143'),
        ('rba', '0020_auto_20211220_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase2envs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools4msp.env')),
                ('phase_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rba.csphase2')),
            ],
        ),
        migrations.AddField(
            model_name='csphase2',
            name='env_list',
            field=models.ManyToManyField(blank=True, through='rba.Phase2envs', to='tools4msp.Env', verbose_name='Environmental Components'),
        ),
    ]
