# Generated by Django 3.2.9 on 2021-12-21 11:58

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rba', '0021_auto_20211221_0824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phase2pressures',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='phase2pressures',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='phase2pressures',
            name='phase_2',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, to='rba.csphase2'),
        ),
    ]
