# Generated by Django 3.2.9 on 2021-12-21 12:02

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rba', '0022_auto_20211221_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase2pressures',
            name='phase_2',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase2pressures_objects', to='rba.csphase2'),
        ),
    ]
