# Generated by Django 3.2.9 on 2021-12-23 11:29

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rba', '0024_alter_cs_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase2pressures',
            name='pressure_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('main', 'Main Pressure'), ('bg', 'Background Pressure')], max_length=7, null=True),
        ),
    ]
