# Generated by Django 3.2.9 on 2021-12-23 11:40

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rba', '0025_phase2pressures_pressure_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phase2uses',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='phase2uses',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='phase2uses',
            name='phase_2',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase2uses_objects', to='rba.csphase2'),
        ),
    ]
