# Generated by Django 3.2.9 on 2021-12-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rba', '0026_auto_20211223_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs',
            name='ecosystem_services',
            field=models.TextField(blank=True, null=True, verbose_name='1.3 Define core Ecosystem Services'),
        ),
        migrations.AlterField(
            model_name='cs',
            name='future_scenarios',
            field=models.TextField(blank=True, null=True, verbose_name='1.4 Define future scenarios'),
        ),
        migrations.AlterField(
            model_name='cs',
            name='policy_objectives',
            field=models.TextField(blank=True, null=True, verbose_name='1.2 Define Policy objectives'),
        ),
        migrations.AlterField(
            model_name='cs',
            name='study_area',
            field=models.TextField(blank=True, null=True, verbose_name='1.1 Define the Study Area'),
        ),
        migrations.AlterField(
            model_name='csphase2',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csphase2',
            name='main_pressures_effects',
            field=models.TextField(blank=True, null=True, verbose_name='2.3 Define main pressures / effects'),
        ),
        migrations.AlterField(
            model_name='csphase2',
            name='main_source_effects',
            field=models.TextField(blank=True, null=True, verbose_name='2.4 Describe main sources of pressures / effects'),
        ),
    ]
