# Generated by Django 3.2.9 on 2022-01-02 12:37

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rba', '0028_alter_cs_map_embed_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyObjectives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('policy_objectives', models.TextField(blank=True, null=True)),
                ('phase_1', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='polobj_objects', to='rba.cs')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
