# Generated by Django 3.2.9 on 2022-01-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rba', '0030_rename_policy_objectives_policyobjectives_polobj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyobjectives',
            name='polobj',
            field=models.TextField(blank=True, null=True, verbose_name='Policy Objective'),
        ),
    ]
