# Generated by Django 3.2.9 on 2022-01-02 17:27

from django.db import migrations, models
import multiselectfield.db.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rba', '0031_alter_policyobjectives_polobj'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase2uses',
            name='layer',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='phase2uses',
            name='use_description',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='phase2uses',
            name='use_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('main', 'Main Use'), ('sec', 'Secondary Use')], max_length=8, null=True),
        ),
    ]
