# Generated by Django 3.2.9 on 2022-01-02 18:00

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rba', '0032_auto_20220102_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='FutureScenarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('future_scen', models.TextField(blank=True, null=True, verbose_name='Future Scenarios')),
                ('phase_1', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='futscen_objects', to='rba.cs')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
