# Generated by Django 3.2.9 on 2022-01-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rba', '0033_futurescenarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='futurescenarios',
            name='future_scen_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Scenario Description'),
        ),
    ]
