# Generated by Django 3.2.9 on 2022-01-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rba', '0034_futurescenarios_future_scen_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyobjectives',
            name='polobj_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Policy Objective Description'),
        ),
    ]
