# Generated by Django 3.2.9 on 2022-01-04 16:01

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rba', '0036_auto_20220104_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase2envs',
            name='phase_2',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase2env_objects', to='rba.csphase2'),
        ),
    ]
