# Generated by Django 3.2.9 on 2022-01-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rba', '0040_alter_csphase2_main_environmental_responses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csphase2',
            name='impact_chain',
            field=models.TextField(blank=True, null=True, verbose_name='2.6 Source / Pressure / Pathway / Receptor Relationships'),
        ),
    ]
