# Generated by Django 3.2.9 on 2022-01-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rba', '0041_alter_csphase2_impact_chain'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase2pressures',
            name='data_source',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
    ]
