# Generated by Django 3.2.9 on 2022-01-11 14:23

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0028_auto_20211213_1143'),
        ('rba', '0042_phase2pressures_data_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Path_pres_env',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('env_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools4msp.env')),
                ('phase_2', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathpe_objects', to='rba.csphase2')),
                ('pressure_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools4msp.pressure')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Path_use_pres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('phase_2', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathup_objects', to='rba.csphase2')),
                ('pressure_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools4msp.pressure')),
                ('use_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools4msp.use')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Path',
        ),
    ]
