# Generated by Django 3.2.9 on 2022-01-11 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0028_auto_20211213_1143'),
        ('rba', '0044_auto_20220111_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='path_use_pres',
            name='use_list',
        ),
        migrations.AddField(
            model_name='path_use_pres',
            name='use_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tools4msp.use'),
            preserve_default=False,
        ),
    ]
