# Generated by Django 3.2.9 on 2022-01-13 15:58

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rba', '0045_auto_20220111_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs',
            name='es_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('hb', 'Habitat Maintenance'), ('cs', 'Carbon Sequestration'), ('fp', 'Food provision'), ('wq', 'Water Quality'), ('fm', 'Fish Migration Route'), ('ba', 'Buffering Against Anoxia'), ('rt', 'Recreation and Tourism'), ('cr', 'Climate Regulation')], max_length=23, null=True),
        ),
    ]
