# Generated by Django 3.2.9 on 2022-01-13 16:10

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rba', '0046_alter_cs_es_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs',
            name='es_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Habitat Maintenance', 'Habitat Maintenance'), ('Carbon Sequestration', 'Carbon Sequestration'), ('Food provision', 'Food provision'), ('Water Quality', 'Water Quality'), ('Fish Migration Route', 'Fish Migration Route'), ('Buffering Against Anoxia', 'Buffering Against Anoxia'), ('Recreation and Tourism', 'Recreation and Tourism'), ('Climate Regulation', 'Climate Regulation')], max_length=157, null=True),
        ),
    ]
