# Generated by Django 3.2.9 on 2022-01-14 15:32

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rba', '0047_alter_cs_es_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase2envs',
            name='env_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('main', 'Main Use'), ('sec', 'Background Use')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='phase2uses',
            name='use_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('main', 'Main Use'), ('sec', 'Background Use')], max_length=8, null=True),
        ),
    ]
