# Generated by Django 3.2.9 on 2022-01-14 15:34

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rba', '0048_auto_20220114_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase2envs',
            name='env_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('main', 'Main Environmental Component'), ('sec', 'Background Environmental Component')], max_length=8, null=True),
        ),
    ]
