# Generated by Django 3.2.9 on 2022-01-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rba', '0049_alter_phase2envs_env_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase2envs',
            name='data_source',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='phase2envs',
            name='layer',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='phase2uses',
            name='data_source',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
    ]
