# Generated by Django 3.2.9 on 2022-01-14 15:38

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rba', '0050_auto_20220114_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase2envs',
            name='data_description',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Data Source description'),
        ),
        migrations.AddField(
            model_name='phase2pressures',
            name='data_description',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Data Source description'),
        ),
        migrations.AddField(
            model_name='phase2uses',
            name='data_description',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Data Source description'),
        ),
    ]
