# Generated by Django 3.2.9 on 2022-01-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rba', '0052_csphase3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CSphase3',
        ),
        migrations.AddField(
            model_name='csphase2',
            name='mana_meas',
            field=models.TextField(blank=True, null=True, verbose_name='3.2 Define Management Measures'),
        ),
    ]
