# Generated by Django 3.2.9 on 2022-01-17 11:11

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rba', '0055_auto_20220117_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecoservice',
            name='ecoobj',
        ),
        migrations.RemoveField(
            model_name='ecoservice',
            name='ecoobj_desc',
        ),
        migrations.AddField(
            model_name='ecoservice',
            name='code',
            field=models.TextField(blank=True, null=True, verbose_name='Ecosystem Service Code'),
        ),
        migrations.AddField(
            model_name='ecoservice',
            name='data_description',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Ecosystem Service Description'),
        ),
        migrations.AddField(
            model_name='ecoservice',
            name='data_source',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='ecoservice',
            name='link',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
    ]
