# Generated by Django 3.2.9 on 2022-01-17 11:20

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rba', '0056_auto_20220117_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecoservice',
            name='Title',
            field=models.TextField(blank=True, null=True, verbose_name='Ecosystem Service'),
        ),
        migrations.AlterField(
            model_name='ecoservice',
            name='code',
            field=models.TextField(blank=True, null=True, verbose_name='Ecosystem Service'),
        ),
        migrations.AlterField(
            model_name='ecoservice',
            name='es_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Biotic', 'Biotic'), ('Abiotic', 'Abiotic')], max_length=14, null=True),
        ),
    ]
