# Generated by Django 3.2.9 on 2022-01-17 11:29

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rba', '0058_auto_20220117_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecoservice',
            old_name='data_description',
            new_name='es_description',
        ),
        migrations.RemoveField(
            model_name='ecoservice',
            name='code',
        ),
        migrations.RemoveField(
            model_name='ecoservice',
            name='data_source',
        ),
        migrations.RemoveField(
            model_name='ecoservice',
            name='link',
        ),
        migrations.AlterField(
            model_name='ecoservice',
            name='bio_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Biotic', 'Biotic'), ('Abiotic', 'Abiotic')], max_length=14, null=True, verbose_name='Section Type'),
        ),
        migrations.AlterField(
            model_name='ecoservice',
            name='es_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Provisioning services', 'Provisioning services'), ('Regulating and Maintenance Services', 'Regulating and Maintenance Services'), ('Cultural Services', 'Cultural Services')], max_length=75, null=True, verbose_name='Section'),
        ),
    ]
