# Generated by Django 3.2.9 on 2022-01-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rba', '0059_auto_20220117_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csphase2',
            name='main_environmental_responses',
            field=models.TextField(blank=True, null=True, verbose_name='2.5 Describe main environmental receptors'),
        ),
    ]
