# Generated by Django 3.2.9 on 2022-01-17 16:48

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rba', '0060_alter_csphase2_main_environmental_responses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase2envs',
            name='env_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('main', 'Main Env'), ('sec', 'Background Env')], max_length=8, null=True),
        ),
    ]
