# Generated by Django 3.2.9 on 2022-03-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rba', '0062_docpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csphase2',
            name='impact_chain',
            field=models.TextField(blank=True, null=True, verbose_name='Source / Pressure / Pathway / Receptor Relationships'),
        ),
        migrations.AlterField(
            model_name='csphase2',
            name='main_environmental_responses',
            field=models.TextField(blank=True, null=True, verbose_name='Describe main environmental receptors'),
        ),
        migrations.AlterField(
            model_name='csphase2',
            name='main_pressures_effects',
            field=models.TextField(blank=True, null=True, verbose_name='Define main pressures / effects'),
        ),
        migrations.AlterField(
            model_name='csphase2',
            name='main_source_effects',
            field=models.TextField(blank=True, null=True, verbose_name='Describe main sources of pressures / effects'),
        ),
    ]
