# Generated by Django 3.2.9 on 2022-03-10 14:14

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rba', '0063_auto_20220310_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManaMeas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('manamea', models.TextField(blank=True, null=True, verbose_name='Management Measures')),
                ('manamea_desc', models.TextField(blank=True, null=True, verbose_name='Management Measure Description')),
                ('phase_2', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='manamea_objects', to='rba.csphase2')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
