# Generated by Django 3.2.9 on 2022-03-10 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rba', '0064_manameas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cs',
            options={'verbose_name': 'Case Study', 'verbose_name_plural': 'Case Studies'},
        ),
    ]
