# Generated by Django 3.2.9 on 2022-03-10 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rba', '0065_alter_cs_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csphase2',
            options={'verbose_name': 'Risk Configuration', 'verbose_name_plural': 'Risk Configurations'},
        ),
    ]
