# Generated by Django 3.2.9 on 2022-03-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rba', '0066_alter_csphase2_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managementmeasures',
            name='manameas_desc',
        ),
        migrations.AlterField(
            model_name='managementmeasures',
            name='manameas',
            field=models.TextField(blank=True, null=True, verbose_name='Description Item'),
        ),
    ]
