# Generated by Django 3.2.9 on 2022-03-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rba', '0067_auto_20220310_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manameas',
            name='manamea_desc',
        ),
        migrations.AlterField(
            model_name='manameas',
            name='manamea',
            field=models.TextField(blank=True, null=True, verbose_name='Description Item'),
        ),
    ]
