# Generated by Django 3.2.9 on 2022-04-28 10:34

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0028_auto_20211213_1143'),
        ('rba', '0072_csphase2_image_smatrix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase2w',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('phase_2', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase2w_objects', to='rba.csphase2')),
                ('w_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools4msp.weight')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='csphase2',
            name='w_list',
            field=models.ManyToManyField(blank=True, through='rba.Phase2w', to='tools4msp.Weight', verbose_name='Weights'),
        ),
    ]
