# Generated by Django 3.2.9 on 2022-04-28 12:08

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0028_auto_20211213_1143'),
        ('rba', '0073_auto_20220428_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Path_w',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('phase_2', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathw_objects', to='rba.csphase2')),
                ('w_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools4msp.weight')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
