# Generated by Django 3.1.7 on 2022-07-12 13:58

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rba', '0075_csphase2_image_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase2envs',
            name='env_type',
        ),
        migrations.RemoveField(
            model_name='phase2pressures',
            name='pressure_type',
        ),
        migrations.RemoveField(
            model_name='phase2uses',
            name='use_type',
        ),
        migrations.AddField(
            model_name='phase2envs',
            name='relevance',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], max_length=5, null=True, verbose_name='Overall relevance'),
        ),
        migrations.AddField(
            model_name='phase2pressures',
            name='relevance',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], max_length=5, null=True, verbose_name='Overall relevance'),
        ),
        migrations.AddField(
            model_name='phase2uses',
            name='relevance',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], max_length=5, null=True, verbose_name='Overall relevance'),
        ),
    ]
