# Generated by Django 3.1.7 on 2022-07-19 08:11

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rba', '0080_auto_20220718_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futurescenarios',
            name='future_scen_desc',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name=' Description'),
        ),
    ]
