# Generated by Django 3.1.7 on 2022-07-19 08:27

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rba', '0081_auto_20220719_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyobjectives',
            name='polobj_desc',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Policy Objective Description'),
        ),
    ]
