# Generated by Django 3.2.9 on 2022-08-09 08:34

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rba', '0082_auto_20220719_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futurescenarios',
            name='driven',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('BG', 'Blue Economy driven'), ('CC', 'Climate Change or Conservation driven')], max_length=5, null=True, verbose_name='Driven By'),
        ),
    ]
